sudo: false
language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/sidekiq_4_0.gemfile
  - gemfiles/sidekiq_4_1.gemfile
  - gemfiles/sidekiq_4_2.gemfile
  - gemfiles/sidekiq_5_0.gemfile
  - gemfiles/sidekiq_5_1.gemfile
services:
  - redis-server
cache: bundler
script:
  - "bundle exec rake spec"
  - "bundle exec rubocop -D"
notifications:
  email: false
